# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
gitlab_runner:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/gitlab_runner/**"
          - "molecule/gitlab_runner/**"
          - ".github/workflows/gitlab_runner.yml"
gitlab:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/gitlab/**"
          - "molecule/gitlab/**"
          - ".github/workflows/gitlab.yml"
haproxy:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/haproxy/**"
          - "molecule/haproxy/**"
          - ".github/workflows/haproxy.yml"
keepalived:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/keepalived/**"
          - "molecule/keepalived/**"
          - ".github/workflows/keepalived.yml"
netplan:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/netplan/**"
          - "molecule/netplan/**"
          - ".github/workflows/netplan.yml"
redis:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/redis/**"
          - "molecule/redis/**"
          - ".github/workflows/redis.yml"
ssh_keys:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/ssh_keys/**"
          - "molecule/ssh_keys/**"
          - ".github/workflows/ssh_keys.yml"
unattended_upgrades:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/unattended_upgrades/**"
          - "molecule/unattended_upgrades/**"
          - ".github/workflows/unattended_upgrades.yml"
zammad:
  - changed-files:
      - any-glob-to-any-file:
          - "roles/zammad/**"
          - "molecule/zammad/**"
          - ".github/workflows/zammad.yml"
