---
# Play to install dependencies.
- name: "Prepare"
  hosts: "all"
  tasks:
    - name: "Install dependencies"
      ansible.builtin.apt:
        name:
          - "sudo"      # for `become` privilege escalation
          - "iproute2"  # for gathering network facts
        update_cache: yes
        state: "present"

...
