# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Converge"
  hosts: "all"
  vars:
    keepalived_unicast_peers:
      - "172.17.0.3"
      - "172.17.0.4"
    keepalived_virtual_ip_address: "172.17.0.20"
  tasks:
    - name: "Include keepalived role"
      ansible.builtin.include_role:
        name: "hifis.toolkit.keepalived"

...
